[book]
authors = ["Philip Dell"]
title = "Documentation Website"
language = "en"
multilingual = false
src = "src"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/pilip-d"
